apiVersion: v1
kind: Service
metadata:
  name: book-inventory-service
spec:
  selector:
    app: book-inventory 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: inventory-port
    - protocol: TCP
      port: 8081
      targetPort: 81
      name: book-catalog-port
  type: LoadBalancer   