apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_URL: "postgresql://mydatabase_945q_user:8Z0Xrnkykb0xPaMZZUUHy4Nw9cnCVOK5@dpg-crcj6vqj1k6c73cn4eug-a.oregon-postgres.render.com/mydatabase_945q"