version: '3'
services:
  book:
    image: jingkang.azurecr.io/book:4
    networks:
      private_network:
        ipv4_address: 172.20.0.3
    ports:
      - "81:81"
    environment:
      - DATABASE_URL=postgresql://mydatabase_945q_user:8Z0Xrnkykb0xPaMZZUUHy4Nw9cnCVOK5@dpg-crcj6vqj1k6c73cn4eug-a.oregon-postgres.render.com/mydatabase_945q
  
  inventory:
    image: jingkang.azurecr.io/inventory:2
    networks:
      private_network:
        ipv4_address: 172.20.0.4
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://mydatabase_945q_user:8Z0Xrnkykb0xPaMZZUUHy4Nw9cnCVOK5@dpg-crcj6vqj1k6c73cn4eug-a.oregon-postgres.render.com/mydatabase_945q

networks:
  private_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24